language: ruby
sudo: false
rvm:
  - 2.1.5
before_script:
  - psql -c 'create database distance_matrix_test;' -U postgres
  - bundle exec rake db:create db:structure:load db:migrate
cache: bundler
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: fdc0e787cb32fe5b3b22701813acc8032e2cd795e009dfe9874368e0de8033ad
